name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Set up Clojure
      uses: DeLaGuardo/setup-clojure@10.3
      with:
        cli: latest
    
    - name: List Directory Contents
      run: ls -a

    - name: Install dependencies
      run: npm install
    
    - name: Build the project
      run: npx shadow-cljs release app

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: resources/public/js
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build
        path: resources/public/js
        
    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.IP_ADDRESS }} >> ~/.ssh/known_hosts  

    - name: Start & Add SSH keys
      run: |
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_ed25519

    - name: Upload build artifacts to server
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp -r -P 22 resources/public/js/ ${{ secrets.SSH_USERNAME }}@${{ secrets.IP_ADDRESS }}:/tmp/build/

    - name: Deploy to server using rsync
      run: |
        ssh -i ~/.ssh/id_ed25519 -p 22 ${{ secrets.SSH_USERNAME }}@${{ secrets.IP_ADDRESS }} \
          "sudo rsync -avz --delete /tmp/build/resources/public/js/ /var/www/lorelailyons.me/html"

    - name: Restart server
      run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.IP_ADDRESS }} 'sudo systemctl reload nginx'