name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Set up Clojure
      uses: DeLaGuardo/setup-clojure@10.3
      with:
        cli: latest
    
    - name: List Directory Contents
      run: ls -a

    - name: Install dependencies
      run: npm install
    
    - name: Build the project
      run: npx shadow-cljs release app

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: resources/public/js
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.IP_ADDRESS }} >> ~/.ssh/known_hosts  

    - name: Start & Add SSH keys
      run: |
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_ed25519

    - name: Deploy to server
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.IP_ADDRESS }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "path/to/build/**/*"
        target: "/path/on/server"

    - name: Restart server
      run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.IP_ADDRESS }} 'sudo systemctl reload nginx'