name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Set up Clojure
      uses: DeLaGuardo/setup-clojure@10.3
      with:
        cli: latest
    
    - name: Install dependencies
      run: npm install
    
    - name: Build the project
      run: npx shadow-cljs release app

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: resources/public/js
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build

    - name: Deploy static assets
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.IP_ADDRESS }} >> ~/.ssh/known_hosts  

    - name: Deploy static assets
      run: |
        rsync -avz --delete resources/public/js/ root@${{ secrets.IP_ADDRESS }}:/Projects/Clojure/Portfolio/resources/public/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
